scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:9100']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9100']

  - job_name: 'ride-service'
    static_configs:
      - targets: ['ride-service:9100']

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:9100']
